name: Ci

on:
    workflow_dispatch:
    push:
        branches: [ master ]
    pull_request_target:
      types: [opened, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get User Permission
              id: checkAccess
              uses: actions-cool/check-user-permission@v2
              with:
                require: write
                username: ${{ github.triggering_actor }}

            - name: Check User Permission
              if: steps.checkAccess.outputs.require-result == 'false'
              run: |
                echo "${{ github.triggering_actor }} does not have permissions on this repo."
                echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
                echo "Job originally triggered by ${{ github.actor }}"
                exit 1

            - name: Checkout
              uses: actions/checkout@v3
              with:
                ref: ${{  github.event.pull_request.head.sha }}

            - name: Test secrets
              run: |
                if [[ "x${{ secrets.TEST_SECRET }}" == "xval" ]]; then
                  echo "Access to secrets"
                else
                  echo "No access to secrets"
                  exit 1
                fi

            - name: Checkout agbcc
              uses: actions/checkout@master
              with:
                path: agbcc
                repository: jiangzhengwenjz/agbcc

            - name: Install binutils
              run: |
               sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi

            - name: Install agbcc
              run: |
                ./build.sh
                ./install.sh ../
                echo $PWD >> "$GITHUB_PATH"
              working-directory: agbcc

            - name: Build preproc
              run: |
                make
              working-directory: tools/preproc

            - name: Build aif2pcm
              run: |
                make
              working-directory: tools/aif2pcm

            - name: Get roms
              uses: actions/checkout@master
              with:
                ref: main
                path: baseroms
                repository: YohannDR/Roms
                ssh-key: ${{ secrets.ROMS_REPO }}
            
            - name: Move roms
              run: |
                cp baseroms/* .

            - name: Check
              run: |
                chmod +x check_roms.sh
                ./check_roms.sh
